export const CLIENTS_ROUTE = '/clients'
export const CLIENT_ROUTE = '/client'
export const BOTS_ROUTE = '/bots'
export const HISTORY_ROUTE = '/history'
export const LOGIN_ROUTE = '/login'
export const BEARS_ROUTE = '/bears'
export const ADMIN_ROUTE = '/'
